"use client";
import { useEffect, useState } from "react";
import { Check, Languages, ReceiptText, RefreshCw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast, Toaster } from "sonner";
type Row = { id: string; userEmail: string; courseTitle: string; price: number; status: string; createdAt: string };
export default function AdminDashboard({ userEmail }: { userEmail: string }) {
  const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [forbidden, setForbidden] = useState(false);
  async function load() { setLoading(true); const r = await fetch("/api/admin/payments"); if (r.status === 403) setForbidden(true); else if (r.ok) setRows(await r.json()); setLoading(false); }
  useEffect(() => { load(); }, []);
  async function review(id: string, status: "approved" | "rejected") { const r = await fetch("/api/admin/payments", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); if (!r.ok) return toast.error("មិនអាចកែស្ថានភាពបានទេ"); setRows((old) => old.map((row) => row.id === id ? { ...row, status } : row)); toast.success(status === "approved" ? "បានបើកវគ្គឱ្យសិស្ស" : "បានបដិសេធវិក្កយបត្រ"); }
  return <main className="min-h-screen bg-[#f5f9ff] text-slate-950"><Toaster richColors/><header className="border-b border-blue-100 bg-white"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-4 sm:px-6"><a href="/" className="flex items-center gap-2 font-black text-blue-950"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-blue-600 text-white"><Languages/></span>BlueLingo Admin</a><div className="text-right"><p className="text-sm font-bold">ម្ចាស់វេបសាយ</p><p className="text-xs text-slate-500">{userEmail}</p></div></div></header><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="flex items-end justify-between"><div><p className="eyebrow">Payment review</p><h1 className="section-title">វិក្កយបត្ររបស់សិស្ស</h1></div><Button variant="outline" onClick={load}><RefreshCw/> Refresh</Button></div>{forbidden ? <div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-900"><h2 className="font-black">គណនីនេះមិនទាន់កំណត់ជា Admin</h2><p className="mt-2">សូមដាក់ Email នេះក្នុង ADMIN_EMAILS របស់វេបសាយ៖ {userEmail}</p></div> : <div className="mt-8 overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-xl shadow-blue-900/5"><div className="hidden grid-cols-[1.2fr_1.5fr_.5fr_.6fr_1fr] gap-4 border-b bg-blue-50 px-6 py-4 text-sm font-bold text-blue-900 md:grid"><span>សិស្ស</span><span>វគ្គ</span><span>តម្លៃ</span><span>ស្ថានភាព</span><span>សកម្មភាព</span></div>{loading ? <p className="p-8 text-center text-slate-500">កំពុងទាញទិន្នន័យ...</p> : rows.length ? rows.map((row) => <div key={row.id} className="grid gap-4 border-b border-blue-50 p-5 last:border-0 md:grid-cols-[1.2fr_1.5fr_.5fr_.6fr_1fr] md:items-center md:px-6"><span className="break-all text-sm font-semibold">{row.userEmail}</span><div><p className="font-bold">{row.courseTitle}</p><p className="text-xs text-slate-500">{new Date(row.createdAt).toLocaleString()}</p></div><span className="font-black text-blue-700">${row.price}</span><span className="text-sm font-bold">{row.status}</span><div className="flex gap-2">{row.status === "pending" ? <><button onClick={() => review(row.id,"approved")} className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-100 text-emerald-700" aria-label="អនុម័ត"><Check size={18}/></button><button onClick={() => review(row.id,"rejected")} className="grid h-9 w-9 place-items-center rounded-xl bg-red-100 text-red-700" aria-label="បដិសេធ"><X size={18}/></button></> : <span className="text-xs text-slate-400">បានពិនិត្យរួច</span>}</div></div>) : <div className="p-10 text-center"><ReceiptText className="mx-auto text-blue-300" size={42}/><p className="mt-3 font-bold">មិនទាន់មានវិក្កយបត្រ</p></div>}</div>}</section></main>;
}
