"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, CheckCircle2, ChevronRight, Clock3, GraduationCap, Languages, LockKeyhole, Menu, PlayCircle, ReceiptText, Search, ShieldCheck, Sparkles, Star, Upload, UserRound, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast, Toaster } from "sonner";
import WebMCPBridge from "./webmcp-bridge";

type Course = { id: string; language: "English" | "Chinese"; title: string; level: string; lessons: number; duration: string; price: number; color: string; icon: string; rating: string };
type Payment = { id: string; courseId: string; courseTitle: string; price: number; status: "pending" | "approved" | "rejected"; createdAt: string };
const courses: Course[] = [
  { id: "english-starter", language: "English", title: "អង់គ្លេសសម្រាប់អ្នកចាប់ផ្តើម", level: "Beginner", lessons: 24, duration: "8 សប្ដាហ៍", price: 19, color: "from-blue-600 to-cyan-400", icon: "EN", rating: "4.9" },
  { id: "english-work", language: "English", title: "អង់គ្លេសសម្រាប់ការងារ", level: "Intermediate", lessons: 32, duration: "10 សប្ដាហ៍", price: 29, color: "from-indigo-600 to-blue-400", icon: "EN", rating: "4.8" },
  { id: "chinese-starter", language: "Chinese", title: "ភាសាចិនកម្រិតដំបូង HSK 1", level: "Beginner", lessons: 28, duration: "9 សប្ដាហ៍", price: 22, color: "from-sky-600 to-blue-400", icon: "中", rating: "4.9" },
  { id: "chinese-business", language: "Chinese", title: "ភាសាចិនសម្រាប់អាជីវកម្ម", level: "Advanced", lessons: 36, duration: "12 សប្ដាហ៍", price: 35, color: "from-blue-700 to-indigo-500", icon: "商", rating: "4.7" },
];

export default function LearningApp({ user, signInPath, signOutPath }: { user: { name: string; email: string } | null; signInPath: string; signOutPath: string }) {
  const [language, setLanguage] = useState("All"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Course | null>(null); const [payments, setPayments] = useState<Payment[]>([]); const [uploading, setUploading] = useState(false); const [mobileMenu, setMobileMenu] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const filtered = useMemo(() => courses.filter((c) => (language === "All" || c.language === language) && c.title.toLowerCase().includes(query.toLowerCase())), [language, query]);
  useEffect(() => { if (user) fetch("/api/payments").then(async (r) => r.ok ? await r.json() as Payment[] : []).then(setPayments).catch(() => undefined); }, [user]);
  async function uploadReceipt(file: File) { if (!selected) return; setUploading(true); const form = new FormData(); form.set("receipt", file); form.set("courseId", selected.id); form.set("courseTitle", selected.title); form.set("price", String(selected.price)); try { const response = await fetch("/api/payments", { method: "POST", body: form }); const data = await response.json() as Payment & { error?: string }; if (!response.ok) throw new Error(data.error || "Upload failed"); setPayments((old) => [data, ...old]); setSelected(null); toast.success("វិក្កយបត្របានផ្ញើទៅ Admin រួចហើយ"); } catch (error) { toast.error(error instanceof Error ? error.message : "មិនអាច Upload បានទេ"); } finally { setUploading(false); } }
  return <main className="min-h-screen bg-[#f5f9ff] text-slate-950">
    <Toaster position="top-center" richColors />
    <WebMCPBridge startEnrollment={(id) => { const course = courses.find((item) => item.id === id); if (!course) return false; setSelected(course); return true; }} />
    <header className="sticky top-0 z-40 border-b border-blue-100 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><a href="#top" className="flex items-center gap-2.5"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-200"><Languages size={22}/></span><span className="text-xl font-black tracking-tight text-blue-950">Blue<span className="text-blue-600">Lingo</span></span></a><nav className="hidden items-center gap-7 md:flex"><a className="nav-link" href="#courses">វគ្គសិក្សា</a><a className="nav-link" href="#how">របៀបរៀន</a><a className="nav-link" href="#dashboard">ការសិក្សារបស់ខ្ញុំ</a></nav><div className="hidden items-center gap-3 md:flex">{user ? <><div className="hidden text-right lg:block"><p className="max-w-44 truncate text-sm font-bold">{user.name}</p><p className="max-w-44 truncate text-xs text-slate-500">{user.email}</p></div><a className="rounded-xl border border-blue-200 px-4 py-2 text-sm font-bold text-blue-700" href={signOutPath} target="_top">ចាកចេញ</a></> : <a className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white shadow-lg shadow-blue-200" href={signInPath} target="_top">ចូលគណនី</a>}</div><button className="rounded-xl p-2 text-blue-900 md:hidden" onClick={() => setMobileMenu(!mobileMenu)} aria-label="បើកម៉ឺនុយ">{mobileMenu ? <X/> : <Menu/>}</button></div>{mobileMenu && <div className="border-t border-blue-100 bg-white px-4 py-4 md:hidden"><a className="mobile-link" href="#courses">វគ្គសិក្សា</a><a className="mobile-link" href="#dashboard">ការសិក្សារបស់ខ្ញុំ</a>{user ? <a className="mobile-link text-red-600" href={signOutPath} target="_top">ចាកចេញ</a> : <a className="mobile-link text-blue-700" href={signInPath} target="_top">ចូលគណនី</a>}</div>}</header>
    <section id="top" className="hero-grid overflow-hidden bg-blue-950 text-white"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:px-8 lg:py-20"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-blue-400/30 bg-blue-400/10 px-4 py-2 text-sm font-semibold text-blue-100"><Sparkles size={16}/> រៀនគ្រប់ទីកន្លែង គ្រប់ពេលវេលា</div><h1 className="max-w-3xl text-4xl font-black leading-[1.18] tracking-tight sm:text-5xl lg:text-6xl">បើកទ្វារទៅកាន់<br/><span className="text-cyan-300">ភាសាថ្មីរបស់អ្នក</span></h1><p className="mt-5 max-w-xl text-lg leading-8 text-blue-100/85">រៀនភាសាអង់គ្លេស និងចិនជាមួយវីដេអូមេរៀនជាភាសាខ្មែរ លំហាត់អនុវត្ត និងការតាមដានវឌ្ឍនភាព។</p><div className="mt-8 flex flex-wrap gap-3"><a className="rounded-2xl bg-white px-6 py-3.5 font-bold text-blue-700 shadow-xl" href="#courses">មើលវគ្គសិក្សា</a><a className="rounded-2xl border border-blue-300/30 bg-blue-800/60 px-6 py-3.5 font-bold" href="#how">របៀបដំណើរការ</a></div></div><div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-8 rounded-full bg-blue-500/20 blur-3xl"/><div className="relative rounded-[2rem] border border-white/15 bg-white/10 p-5 shadow-2xl backdrop-blur-xl"><div className="rounded-[1.5rem] bg-white p-5 text-slate-900"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-semibold text-blue-600">មេរៀនថ្ងៃនេះ</p><h2 className="mt-1 text-xl font-black">Daily Conversations</h2></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-100 text-blue-700"><PlayCircle/></span></div><div className="mb-4 h-40 rounded-2xl bg-gradient-to-br from-blue-600 via-blue-500 to-cyan-400 p-6 text-white"><p className="text-sm text-blue-100">Lesson 04</p><p className="mt-8 text-2xl font-black">At the coffee shop</p><p className="mt-2 text-sm text-blue-50">12:45 minutes</p></div><div className="flex items-center justify-between text-sm font-bold"><span>វឌ្ឍនភាពវគ្គ</span><span className="text-blue-600">42%</span></div><Progress value={42} className="mt-3 h-2 bg-blue-100"/></div></div></div></div></section>
    <section id="courses" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">ជ្រើសរើសការសិក្សា</p><h2 className="section-title">វគ្គដែលសមនឹងគោលដៅអ្នក</h2></div><div className="relative w-full md:w-72"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={19}/><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full rounded-2xl border border-blue-100 bg-white py-3 pl-11 pr-4 outline-none focus:ring-4 focus:ring-blue-100" placeholder="ស្វែងរកវគ្គ..."/></div></div><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{["All","English","Chinese"].map((item) => <button key={item} onClick={() => setLanguage(item)} className={`whitespace-nowrap rounded-xl px-5 py-2.5 text-sm font-bold ${language === item ? "bg-blue-600 text-white shadow-lg shadow-blue-200" : "border border-blue-100 bg-white text-slate-600"}`}>{item === "All" ? "វគ្គទាំងអស់" : item}</button>)}</div><div className="mt-7 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{filtered.map((course) => <article key={course.id} className="course-card"><div className={`relative h-40 overflow-hidden rounded-[1.35rem] bg-gradient-to-br ${course.color} p-5 text-white`}><div className="absolute -right-8 -top-8 h-28 w-28 rounded-full border-[18px] border-white/10"/><div className="flex items-start justify-between"><span className="grid h-13 w-13 place-items-center rounded-2xl bg-white/20 text-xl font-black">{course.icon}</span><span className="flex items-center gap-1 rounded-full bg-slate-950/20 px-2.5 py-1 text-xs font-bold"><Star size={13} fill="currentColor"/> {course.rating}</span></div><p className="mt-7 text-sm font-semibold text-blue-50">{course.language} · {course.level}</p></div><div className="p-5"><h3 className="min-h-14 text-lg font-extrabold leading-7">{course.title}</h3><div className="mt-4 flex items-center gap-4 text-sm text-slate-500"><span className="flex items-center gap-1.5"><BookOpen size={16}/>{course.lessons} មេរៀន</span><span className="flex items-center gap-1.5"><Clock3 size={16}/>{course.duration}</span></div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-2xl font-black text-blue-700">${course.price}</span><Button onClick={() => setSelected(course)} className="rounded-xl bg-blue-600 font-bold hover:bg-blue-700">ចុះឈ្មោះ <ChevronRight/></Button></div></div></article>)}</div></section>
    <section id="how" className="border-y border-blue-100 bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="text-center"><p className="eyebrow">ងាយត្រឹម 3 ជំហាន</p><h2 className="section-title">ចាប់ផ្ដើមរៀនថ្ងៃនេះ</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[[UserRound,"1","ចូលគណនី","ចូលដោយគណនី ChatGPT របស់អ្នក ដើម្បីរក្សាវឌ្ឍនភាព។"],[ReceiptText,"2","ជ្រើសវគ្គ និងបង់ប្រាក់","ស្កេន KHQR រួច Upload រូបវិក្កយបត្រមួយសន្លឹក។"],[GraduationCap,"3","Admin អនុម័ត និងចូលរៀន","ពេលអនុម័តរួច វគ្គនឹងបើកឱ្យអ្នកភ្លាម។"]].map(([Icon,n,title,text]) => { const C = Icon as typeof UserRound; return <div key={String(n)} className="step-card"><span className="step-number">{String(n)}</span><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-100 text-blue-700"><C/></span><h3 className="mt-5 text-xl font-black">{String(title)}</h3><p className="mt-2 leading-7 text-slate-600">{String(text)}</p></div>})}</div></div></section>
    <section id="dashboard" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="rounded-[2rem] bg-blue-950 p-6 text-white shadow-2xl sm:p-9"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-bold uppercase tracking-widest text-cyan-300">Student Dashboard</p><h2 className="mt-2 text-3xl font-black">ការសិក្សារបស់ខ្ញុំ</h2></div>{!user && <a className="self-start rounded-xl bg-white px-5 py-3 font-bold text-blue-700" href={signInPath} target="_top">ចូលគណនីដើម្បីមើល</a>}</div>{user && <Tabs defaultValue="courses" className="mt-7"><TabsList className="bg-white/10"><TabsTrigger value="courses">វគ្គរបស់ខ្ញុំ</TabsTrigger><TabsTrigger value="payments">ការទូទាត់</TabsTrigger></TabsList><TabsContent value="courses"><div className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-5">{payments.some(p => p.status === "approved") ? payments.filter(p => p.status === "approved").map(p => <div key={p.id} className="flex items-center gap-4"><CheckCircle2 className="text-cyan-300"/><div><p className="font-bold">{p.courseTitle}</p><p className="text-sm text-blue-200">វគ្គបានបើក · ចូលរៀនបាន</p></div></div>) : <div className="flex items-center gap-4"><LockKeyhole className="text-blue-300"/><div><p className="font-bold">មិនទាន់មានវគ្គដែលបានបើក</p><p className="text-sm text-blue-200">ជ្រើសវគ្គ និងផ្ញើវិក្កយបត្រ ដើម្បីចាប់ផ្ដើម។</p></div></div>}</div></TabsContent><TabsContent value="payments"><div className="mt-5 space-y-3">{payments.length ? payments.map(p => <div key={p.id} className="flex flex-col justify-between gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 sm:flex-row sm:items-center"><div><p className="font-bold">{p.courseTitle}</p><p className="text-sm text-blue-200">${p.price} · {new Date(p.createdAt).toLocaleDateString()}</p></div><span className={`self-start rounded-full px-3 py-1 text-sm font-bold ${p.status === "approved" ? "bg-emerald-400/20 text-emerald-200" : p.status === "rejected" ? "bg-red-400/20 text-red-200" : "bg-amber-400/20 text-amber-200"}`}>{p.status === "approved" ? "បានអនុម័ត" : p.status === "rejected" ? "បានបដិសេធ" : "កំពុងរង់ចាំ"}</span></div>) : <p className="rounded-2xl bg-white/5 p-5 text-blue-100">មិនទាន់មានការទូទាត់ទេ។</p>}</div></TabsContent></Tabs>}</div></section>
    <footer className="border-t border-blue-100 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 font-black text-blue-950"><Languages size={20} className="text-blue-600"/> BlueLingo</div><p>© 2026 BlueLingo · រៀនដើម្បីអនាគត</p></div></footer>
    <Dialog open={!!selected} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-w-md overflow-hidden rounded-[1.75rem] p-0"><div className="bg-blue-600 p-6 text-white"><DialogHeader><DialogTitle className="text-2xl font-black">បង់ប្រាក់ និងផ្ញើវិក្កយបត្រ</DialogTitle><DialogDescription className="text-blue-100">{selected?.title}</DialogDescription></DialogHeader></div><div className="p-6">{!user ? <div className="text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-100 text-blue-700"><ShieldCheck/></span><h3 className="mt-4 text-xl font-black">សូមចូលគណនីជាមុន</h3><p className="mt-2 text-slate-600">គណនីជួយរក្សាទុកការទូទាត់ និងវឌ្ឍនភាពរបស់អ្នក។</p><a className="mt-5 block rounded-xl bg-blue-600 px-5 py-3 font-bold text-white" href={signInPath} target="_top">ចូលគណនី</a></div> : <><div className="flex items-center justify-between rounded-2xl bg-blue-50 p-4"><div><p className="text-sm text-slate-500">តម្លៃវគ្គ</p><p className="text-2xl font-black text-blue-700">${selected?.price}</p></div><div className="rounded-xl bg-white px-3 py-2 text-right text-xs font-bold text-slate-500 shadow-sm">KHQR<br/><span className="text-blue-700">ABA / Bakong</span></div></div><p className="mt-5 text-sm leading-6 text-slate-600">បន្ទាប់ពីបង់ប្រាក់ សូម Upload រូបវិក្កយបត្រ JPG, PNG ឬ WebP មិនលើស 8MB។</p><input ref={inputRef} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => { const file = e.target.files?.[0]; if (file) uploadReceipt(file); }}/><button disabled={uploading} onClick={() => inputRef.current?.click()} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-blue-200 bg-blue-50 px-5 py-8 font-bold text-blue-700 disabled:opacity-50"><Upload/>{uploading ? "កំពុង Upload..." : "ជ្រើសរូបវិក្កយបត្រ"}</button></>}</div></DialogContent></Dialog>
  </main>;
}
